.TH "src/runtime Directory Reference" 3Version 1.0.0" "Exception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/runtime Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArithmeticException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBFileNotFoundException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIllegalArgumentException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIllegalCastException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIllegalStateException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIndexOutOfBoundsException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBNotFoundException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBNullPointerException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBOutOfMemoryException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPermissionException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBRuntimeException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSocketException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBStackOverflowException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBStackUnderflowException\&.hpp\fP"
.br
.in -1c
