.TH "src/runtime/IndexOutOfBoundsException.hpp" 3Version 1.0.0" "Exception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/runtime/IndexOutOfBoundsException.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IllegalArgumentException\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBjpl::_exception::IndexOutOfBoundsException\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBjpl\fP"
.br
.ti -1c
.RI "namespace \fBjpl::_exception\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An IndexOutOfBounds exception is thrown whenever getting an element whose index is out-of-range of a list is attempted\&. It throws an IllegalArgumentException if Max is greater than Attempted
.PP
\fBDate\fP
.RS 4
2023-04-23 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP
\fBAuthor\fP
.RS 4
Gabriele-P03 
.RE
.PP

.PP
Definition in file \fBIndexOutOfBoundsException\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Exception from the source code\&.
