.TH "jpl::_exception::IllegalArgumentException" 3Version 1.0.0" "Exception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpl::_exception::IllegalArgumentException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IllegalArgumentException\&.hpp>\fP
.PP
Inherits \fBjpl::_exception::RuntimeException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIllegalArgumentException\fP (const char *\fBmsg\fP)"
.br
.ti -1c
.RI "\fBIllegalArgumentException\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBjpl::_exception::RuntimeException\fP
.in +1c
.ti -1c
.RI "\fBRuntimeException\fP (const char *\fBtype_ex\fP, const char *\fBmsg\fP)"
.br
.ti -1c
.RI "\fBRuntimeException\fP (const char *\fBmsg\fP)"
.br
.in -1c

Public Member Functions inherited from \fBjpl::_exception::AbstractException\fP
.in +1c
.ti -1c
.RI "virtual const char * \fBwhat\fP () const _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW override"
.br
.RI "Print the type of the exception which has been thrown with the message that has been passed, too\&. "
.ti -1c
.RI "virtual const char * \fBgetStacktrace\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBjpl::_exception::AbstractException\fP
.in +1c
.ti -1c
.RI "\fBAbstractException\fP (const char *\fBtype_ex\fP)"
.br
.ti -1c
.RI "\fBAbstractException\fP (const char *\fBtype_ex\fP, const char *\fBmsg\fP)"
.br
.in -1c

Protected Attributes inherited from \fBjpl::_exception::AbstractException\fP
.in +1c
.ti -1c
.RI "const char * \fBtype_ex\fP"
.br
.ti -1c
.RI "const char * \fBmsg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBIllegalArgumentException\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jpl::_exception::IllegalArgumentException::IllegalArgumentException (const char * msg)\fC [inline]\fP"

.PP
Definition at line \fB25\fP of file \fBIllegalArgumentException\&.hpp\fP\&.
.SS "jpl::_exception::IllegalArgumentException::IllegalArgumentException ()\fC [inline]\fP"

.PP
Definition at line \fB26\fP of file \fBIllegalArgumentException\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Exception from the source code\&.
