.TH "jpl::_exception::IOException" 3Version 1.0.0" "Exception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpl::_exception::IOException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IOException\&.hpp>\fP
.PP
Inherits \fBjpl::_exception::RuntimeException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIOException\fP (unsigned int \fBerror_code\fP, std::string \fBdescription\fP, std::string \fBmsg\fP)"
.br
.ti -1c
.RI "\fBIOException\fP (unsigned int \fBerror_code\fP, std::string \fBdescription\fP)"
.br
.ti -1c
.RI "\fBIOException\fP (unsigned int \fBerror_code\fP)"
.br
.ti -1c
.RI "\fBIOException\fP (std::string \fBmsg\fP)"
.br
.ti -1c
.RI "\fBIOException\fP ()"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW override"
.br
.RI "Print the type of the exception which has been thrown with the message that has been passed, too\&. "
.in -1c

Public Member Functions inherited from \fBjpl::_exception::RuntimeException\fP
.in +1c
.ti -1c
.RI "\fBRuntimeException\fP (std::string \fBtype_ex\fP, std::string \fBmsg\fP)"
.br
.ti -1c
.RI "\fBRuntimeException\fP (std::string \fBmsg\fP)"
.br
.ti -1c
.RI "\fBRuntimeException\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "virtual const char * \fBwhat\fP () const _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW override"
.br
.RI "Print the type of the exception which has been thrown with the message that has been passed, too\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const unsigned int \fBerror_code\fP"
.br
.ti -1c
.RI "std::string \fBdescription\fP"
.br
.in -1c

Protected Attributes inherited from \fBjpl::_exception::AbstractException\fP
.in +1c
.ti -1c
.RI "std::string \fBtype_ex\fP"
.br
.ti -1c
.RI "std::string \fBmsg\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBjpl::_exception::AbstractException\fP
.in +1c
.ti -1c
.RI "\fBAbstractException\fP (std::string \fBtype_ex\fP)"
.br
.ti -1c
.RI "\fBAbstractException\fP (std::string \fBtype_ex\fP, std::string \fBmsg\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBIOException\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jpl::_exception::IOException::IOException (unsigned int error_code, std::string description, std::string msg)\fC [inline]\fP"

.PP
Definition at line \fB31\fP of file \fBIOException\&.hpp\fP\&.
.SS "jpl::_exception::IOException::IOException (unsigned int error_code, std::string description)\fC [inline]\fP"

.PP
Definition at line \fB32\fP of file \fBIOException\&.hpp\fP\&.
.SS "jpl::_exception::IOException::IOException (unsigned int error_code)\fC [inline]\fP"

.PP
Definition at line \fB33\fP of file \fBIOException\&.hpp\fP\&.
.SS "jpl::_exception::IOException::IOException (std::string msg)\fC [inline]\fP"

.PP
Definition at line \fB34\fP of file \fBIOException\&.hpp\fP\&.
.SS "jpl::_exception::IOException::IOException ()\fC [inline]\fP"

.PP
Definition at line \fB35\fP of file \fBIOException\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const char * jpl::_exception::IOException::what () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Print the type of the exception which has been thrown with the message that has been passed, too\&. 
.PP
\fBReturns\fP
.RS 4
const char* 
.RE
.PP

.PP
Reimplemented from \fBjpl::_exception::AbstractException\fP\&.
.PP
Definition at line \fB37\fP of file \fBIOException\&.hpp\fP\&.
.SH "Field Documentation"
.PP 
.SS "std::string jpl::_exception::IOException::description\fC [protected]\fP"

.PP
Definition at line \fB28\fP of file \fBIOException\&.hpp\fP\&.
.SS "const unsigned int jpl::_exception::IOException::error_code\fC [protected]\fP"

.PP
Definition at line \fB27\fP of file \fBIOException\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Exception from the source code\&.
