.TH "jpl::_exception::SocketException" 3Version 1.0.0" "Exception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpl::_exception::SocketException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SocketException\&.hpp>\fP
.PP
Inherits \fBjpl::_exception::RuntimeException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSocketException\fP (const unsigned int \fBfd\fP, const unsigned int \fBerror_code\fP, std::string \fBmsg\fP)"
.br
.ti -1c
.RI "\fBSocketException\fP (const unsigned int \fBfd\fP, const unsigned int \fBerror_code\fP)"
.br
.ti -1c
.RI "\fBSocketException\fP (const unsigned int \fBfd\fP)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW override"
.br
.RI "Print the type of the exception which has been thrown with the message that has been passed, too\&. "
.in -1c

Public Member Functions inherited from \fBjpl::_exception::RuntimeException\fP
.in +1c
.ti -1c
.RI "\fBRuntimeException\fP (std::string \fBtype_ex\fP, std::string \fBmsg\fP)"
.br
.ti -1c
.RI "\fBRuntimeException\fP (std::string \fBmsg\fP)"
.br
.ti -1c
.RI "\fBRuntimeException\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "virtual const char * \fBwhat\fP () const _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW override"
.br
.RI "Print the type of the exception which has been thrown with the message that has been passed, too\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const unsigned int \fBerror_code\fP"
.br
.ti -1c
.RI "const unsigned int \fBfd\fP"
.br
.in -1c

Protected Attributes inherited from \fBjpl::_exception::AbstractException\fP
.in +1c
.ti -1c
.RI "std::string \fBtype_ex\fP"
.br
.ti -1c
.RI "std::string \fBmsg\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBjpl::_exception::AbstractException\fP
.in +1c
.ti -1c
.RI "\fBAbstractException\fP (std::string \fBtype_ex\fP)"
.br
.ti -1c
.RI "\fBAbstractException\fP (std::string \fBtype_ex\fP, std::string \fBmsg\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBSocketException\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jpl::_exception::SocketException::SocketException (const unsigned int fd, const unsigned int error_code, std::string msg)\fC [inline]\fP"

.PP
Definition at line \fB38\fP of file \fBSocketException\&.hpp\fP\&.
.SS "jpl::_exception::SocketException::SocketException (const unsigned int fd, const unsigned int error_code)\fC [inline]\fP"

.PP
Definition at line \fB39\fP of file \fBSocketException\&.hpp\fP\&.
.SS "jpl::_exception::SocketException::SocketException (const unsigned int fd)\fC [inline]\fP"

.PP
Definition at line \fB44\fP of file \fBSocketException\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char * jpl::_exception::SocketException::what () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Print the type of the exception which has been thrown with the message that has been passed, too\&. 
.PP
\fBReturns\fP
.RS 4
const char* 
.RE
.PP

.PP
Reimplemented from \fBjpl::_exception::AbstractException\fP\&.
.PP
Definition at line \fB46\fP of file \fBSocketException\&.hpp\fP\&.
.SH "Field Documentation"
.PP 
.SS "const unsigned int jpl::_exception::SocketException::error_code\fC [protected]\fP"
The occurred error's code 
.PP
Definition at line \fB31\fP of file \fBSocketException\&.hpp\fP\&.
.SS "const unsigned int jpl::_exception::SocketException::fd\fC [protected]\fP"
The file descriptor of the socket which has caused this exception 
.PP
Definition at line \fB35\fP of file \fBSocketException\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Exception from the source code\&.
