.TH "src/reflection/NoSuchMethodException.hpp" 3Version 1.0.0" "Exception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/reflection/NoSuchMethodException.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./AbstractException\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBjpl::_exception::NoSuchMethodException\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBjpl\fP"
.br
.ti -1c
.RI "namespace \fBjpl::_exception\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A NoSuchMethodException is thrown whenever a method which had been attempted to be get via reflexpr TS or any other kind of reflection feature that will be implemented later in C++, has not been found\&.
.PP
Since reflexpr TS is experimental this exception could seem as useless, indeed it is though for a later feature\&.
.PP
\fBDate\fP
.RS 4
2023-04-22 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP
\fBAuthor\fP
.RS 4
Gabriele-P03 
.RE
.PP

.PP
Definition in file \fBNoSuchMethodException\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Exception from the source code\&.
